name: cropperx
description: An image cropper package made in Flutter. Can be used to crop & rotate images.
version: 1.0.0
homepage: https://github.com/speedkodi/flutter_cropperx

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: