name: cropperx
description: A cropper package made in Flutter. Can be used to crop & rotate images and exporting them to a file.
version: 0.0.2
homepage: https://github.com/speedkodi/flutter_cropperx

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: