name: cropperx
description: An image cropper package made in Flutter. Can be used to crop & rotate images.
version: 1.1.1
homepage: https://github.com/DEVLOCK-inc/flutter_cropperx.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: